services:
  nodered:
    build: .
    image: university-course-monitor/nodered:custom
    container_name: node-red
    ports:
      - "1880:1880"
    volumes:
      - ./workspace:/data
    env_file:
      - .env
    environment:
      - TZ=Europe/Berlin
    restart: unless-stopped
